"""post add score

Revision ID: cbfbea560861
Revises: 02f97846734c
Create Date: 2020-11-04 15:28:27.200955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfbea560861'
down_revision = '02f97846734c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'score')
    # ### end Alembic commands ###
